filename: moleculeqa_llm_baseline_qwen3_0shot
ckpt_path: checkpoints/stage2_dqw2d/epoch=01.ckpt

strategy_name: deepspeed
accelerator: gpu
precision: bf16-mixed
max_steps: 100
accumulate_grad_batches: 64

weight_decay: 0.05
init_lr: 1.0e-4
min_lr: 1.0e-5
warmup_lr: 1.0e-5
warmup_steps: 10
scheduler: None

tune_gnn: False
temperature: 0.1
enable_flash: True
use_dq_encoder: True
freeze_llm: True
brics_gids_enable: True
entropy_gids_enable: True
enable_blending: True
log_every_n_steps: 2
zero_shot: True

llm_baseline: True
llm_model_path: unsloth/Qwen3-8B


