filename: stage2_dqformer_frozen_brics
stage1_path: checkpoints/stage1/stage1_dqformer_brics/last.ckpt

strategy_name: deepspeed
accelerator: gpu
devices:
  - 0
  - 1
precision: bf16-mixed
max_epochs: 2
val_check_interval: 5000
save_every_n_epochs: 2
accumulate_grad_batches: 8

weight_decay: 0.05
init_lr: 1.0e-4
min_lr: 5.0e-6
warmup_lr: 1.0e-6
warmup_steps: 1000
scheduler: linear_warmup_cosine_lr

tune_gnn: False
temperature: 0.1
enable_flash: True
use_dq_encoder: True
use_flash_attention: True
freeze_llm: True
brics_gids_enable: True
entropy_gids_enable: False


