filename: stage2_dqw2d_mistral8b_v2
stage1_path: checkpoints/stage1_dqw2d/last.ckpt

strategy_name: deepspeed
accelerator: gpu
precision: bf16-mixed
max_epochs: 2
val_check_interval: 5000
save_every_n_epochs: 1
accumulate_grad_batches: 16

weight_decay: 0.05
init_lr: 1.0e-4
min_lr: 5.0e-6
warmup_lr: 1.0e-6
warmup_steps: 1000
scheduler: linear_warmup_cosine_lr

tune_gnn: False
temperature: 0.1
enable_flash: True
use_dq_encoder: True
use_flash_attention: True
freeze_llm: True
brics_gids_enable: True
entropy_gids_enable: True
enable_blending: True
llm_backbone: mistralai/Ministral-8B-Instruct-2410
