filename: stage2_v2.1
stage1_path: checkpoints/stage1_v2/epoch=05.ckpt

strategy_name: deepspeed
accelerator: gpu
devices:
  - 0
precision: bf16-mixed
max_epochs: 2
val_check_interval: 5000
save_every_n_epochs: 1
accumulate_grad_batches: 8

weight_decay: 0.05
init_lr: 1.0e-4
min_lr: 5.0e-6
warmup_lr: 1.0e-6
warmup_steps: 1000
scheduler: linear_warmup_cosine_lr

tune_gnn: False
temperature: 0.1
enable_flash: True

