filename: moleculeqa_dqw2d_qwen3
ckpt_path: checkpoints/stage2_dqw2d_qwen3/last.ckpt

strategy_name: deepspeed
accelerator: gpu
precision: bf16-mixed
max_steps: 100
accumulate_grad_batches: 32 # 2 * 128

weight_decay: 0.05
init_lr: 1.0e-4
min_lr: 1.0e-5
warmup_lr: 1.0e-5
warmup_steps: 10
scheduler: None

tune_gnn: False
temperature: 0.1
enable_flash: True
use_dq_encoder: True
freeze_llm: False
brics_gids_enable: True
entropy_gids_enable: True
enable_blending: True
log_every_n_steps: 2
zero_shot: False

