filename: molgen_dqw2d_large
ckpt_path: checkpoints/stage2_dqw2d_large/final.ckpt

strategy_name: deepspeed
accelerator: gpu
precision: bf16-mixed
max_epochs: 5
check_val_every_n_epoch: 1
save_every_n_epochs: 10
accumulate_grad_batches: 64 # 2 * 128

weight_decay: 0.05
init_lr: 1.0e-4
min_lr: 1.0e-5
warmup_lr: 1.0e-5
warmup_steps: 100
scheduler: linear_warmup_cosine_lr

tune_gnn: False
temperature: 0.1
enable_flash: True
use_dq_encoder: True
freeze_llm: False
brics_gids_enable: True
entropy_gids_enable: True
enable_blending: True
zero_shot: False

num_query_tokens: 16
num_layers: 8
num_heads: 8
embed_dim: 512
cross_attention_freq: 1

